# docker-compose.yml
version: "3"
services:
  ##### FRONTEND APP #####
  app:
    extends:
      file: ../base/docker-compose.yml
      service: app
    # image: ${DOCKER_REGISTRY-adtool}/prod-app:${RELEASE_TAG-latest}
  ##### GATEWAY #####
  gateway:
    extends:
      file: ../base/docker-compose.yml
      service: gateway
    # image: ${DOCKER_REGISTRY-adtool}/prod-gateway:${RELEASE_TAG-latest}
  ##### APP DB #####
  app-db:
    extends:
      file: ../base/docker-compose.yml
      service: app-db
  app-db-api:
    extends:
      file: ../base/docker-compose.yml
      service: app-db-api
  ##### EXPE DB #####
  expe-db:
    extends:
      file: ../base/docker-compose.yml
      service: expe-db
  expe-db-api:
    extends:
      file: ../base/docker-compose.yml
      service: expe-db-api
    # image: ${DOCKER_REGISTRY-adtool}/prod-expe-db-api:${RELEASE_TAG-latest}
  ##### AUTODISC SERVER #####
  autodisc-server:
    extends:
      file: ../base/docker-compose.yml
      service: autodisc-server
    # image: ${DOCKER_REGISTRY-adtool}/prod-autodisc-server:${RELEASE_TAG-latest}
  ##### JUPYTER LAB #####
  jupyter:
    extends:
      file: ../base/docker-compose.yml
      service: jupyter
    # image: ${DOCKER_REGISTRY-adtool}/prod-jupyter:${RELEASE_TAG-latest}
