from auto_disc.output_representations.specific.lenia_output_representation import LeniaImageRepresentation
from auto_disc.output_representations.specific.lenia_output_representation_hand_defined import LeniaHandDefinedRepresentation
from auto_disc.output_representations.specific.lenia_image_selector import LeniaImageSelector