# docker-compose.yml
version: "3" # TODO
services:
  ##### FRONTEND APP #####
  app:
    # extends:
    #   file: ../base/docker-compose.yml
    #   service: app
    environment:
      DEBUG: 1
  ##### GATEWAY #####
  gateway:
    # extends:
    #   file: ../base/docker-compose.yml
    #   service: gateway
    extra_hosts:
      - "host.docker.internal:host-gateway" # Useful for debug on Linux
  ##### APP DB #####
  app-db:
    # extends:
    #   file: ../base/docker-compose.yml
    #   service: app-db
    ports:
      - "$EXPOSED_APP_DB_PORT:5432"
  app-db-api:
    # extends:
    #   file: ../base/docker-compose.yml
    #   service: app-db-api
    ports:
      - "$EXPOSED_APP_DB_API_PORT:80"
  ##### EXPE DB #####
  expe-db:
    # extends:
    #   file: ../base/docker-compose.yml
    #   service: expe-db
    ports:
      - "$EXPOSED_EXPE_DB_PORT:27017"
  expe-db-api:
    # extends:
    #   file: ../base/docker-compose.yml
    #   service: expe-db-api
    ports:
      - "$EXPOSED_EXPE_DB_API_PORT:80"
  ##### AUTODISC SERVER #####
  autodisc-server:
    # extends:
    #   file: ../base/docker-compose.yml
    #   service: autodisc-server
    ports:
      - "$EXPOSED_AUTODISC_SERVER_PORT:80"
  ##### JUPYTER LAB #####
  # jupyter:
  #   extends:
  #     file: ../base/docker-compose.yml
  #     service: jupyter
  ##### MONITORING TOOLS #####
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "$DOZZLE_PORT:8080"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "$PGADMIN_PORT:5050"
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
      - "./utils/pgadmin_mapping/servers.json:/pgadmin4/servers.json"
    depends_on:
      - app-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
  mongo-express:
    image: mongo-express
    ports:
      - "$MONGO_EXPRESS_PORT:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: expe-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    depends_on:
      - expe-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
