# docker-compose.yml
version: "3.7" # TODO
services:
  ##### FRONTEND APP #####
  app:
    hostname: app
    build:
      context: ./FrontEndApp
      args:
        - GATEWAY_HOST=${GATEWAY_HOST-127.0.0.1}
        - GATEWAY_PORT=${GATEWAY_PORT-4201}
    environment:
      GATEWAY_HOST: ${GATEWAY_HOST-127.0.0.1}
    ports:
      - "$EXPOSED_APP_PORT:80"
    volumes:
      - "./FrontEndApp/angular_app/src:/usr/src/angular_app/src"
      - "./JupyterLab/Notebooks:/usr/src/notebooks"
    depends_on:
      - gateway
      - jupyter
  ##### GATEWAY #####
  gateway:
    hostname: gateway
    build:
      context: ./Gateway
    environment:
      EXPE_DB_API_HOST: ${EXPE_DB_API_HOST-expe-db-api}
      EXPE_DB_API_PORT: ${EXPE_DB_API_PORT-80}
      APP_DB_API_HOST: app-db-api
      APP_DB_API_PORT: 80
      AUTODISC_SERVER_HOST: ${AUTODISC_SERVER_HOST-autodisc-server}
      AUTODISC_SERVER_PORT: ${AUTODISC_SERVER_PORT-80}
      JUPYTER_HOST: jupyter
      JUPYTER_PORT: 8888
    ports:
      - "$EXPOSED_GATEWAY_PORT:4201"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Useful for debug on Linux
  ##### APP DB #####
  app-db:
    hostname: app-db
    image: postgres:10.16
    command: -p 5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./AppDB/saved_data:/var/lib/postgresql/data"
      - "./AppDB/init_scripts:/docker-entrypoint-initdb.d"
  app-db-api:
    hostname: app-db-api
    image: postgrest/postgrest:v9.0.0.20220531
    environment:
      PGRST_DB_URI: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@app-db:5432/$POSTGRES_DB
      PGRST_DB_SCHEMA: $PGRST_DB_SCHEMA
      PGRST_DB_ANON_ROLE: $PGRST_DB_ANON_ROLE
      PGRST_SERVER_PORT: 80
      PGRST_LOG_LEVEL: info
    depends_on:
      - app-db
  ##### EXPE DB #####
  expe-db:
    hostname: expe-db
    image: mongo
    command: mongod --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - "./ExpeDB/saved_data:/data/db"
  expe-db-api:
    hostname: expe-db-api
    build:
      context: ./ExpeDB/API
    environment:
      MONGODB_HOST: expe-db
      MONGODB_PORT: 27017
    volumes:
      - "./ExpeDB/API/flask_app:/usr/src/flask_app"
    depends_on:
      - expe-db
  ##### AUTODISC SERVER #####
  autodisc-server:
    hostname: autodisc-server
    #platform: linux/amd64
    build:
      context: ../base/AutoDiscServer
    environment:
      EXPEDB_CALLER_HOST: expe-db-api
      EXPEDB_CALLER_PORT: 80
      APPDB_CALLER_HOST: app-db-api
      APPDB_CALLER_PORT: 80
      SSH_AUTH_SOCK: /ssh-agent
      SSH_CONFIG_FILE: "/root/.ssh/config"
    volumes:
      - "./AutoDiscServer/flask_app:/usr/src/services/flask_app"
      - "./AutoDiscServer/libs:/usr/src/libs"
      - "../../configs/:/usr/src/configs"
      - "$SSH_CONFIG_FOLDER:/root/.ssh:ro"
      - "$SSH_SOCK_PATH:/ssh-agent"
    depends_on:
      - expe-db-api
      - app-db-api
  ##### JUPYTER LAB #####
  jupyter:
    hostname: jupyter
   # platform: linux/amd64
    build:
      context: ./JupyterLab
    environment:
      EXPEDB_CALLER_HOST: ${EXPE_DB_API_HOST-expe-db-api}
      EXPEDB_CALLER_PORT: ${EXPE_DB_API_PORT-80}
      PYTHONPATH: "/usr/src/auto_disc_db"
    volumes:
      - "./JupyterLab/Notebooks:/usr/src/notebooks"
      - "../base/AutoDiscServer/libs/auto_disc_db:/usr/src/auto_disc_db"
