from auto_disc.input_wrappers.generic.dummy_input_wrapper import DummyInputWrapper
from auto_disc.input_wrappers.generic.times_n_input_wrapper import TimesNInputWrapper
from auto_disc.input_wrappers.generic.cppn import CppnInputWrapper