name: 
  tower
ssh_configuration: 
  tower
work_path:
  /home/mayalen/code/09-AutoDisc/experiments/
local_tmp_path:
  /tmp/auto_disc
execution:
  bash additional_files/tower.sh $NB_SEEDS $ARGS > $EXPE_ID
cancellation:
  for pid in $RUN_ID; do kill -9 $pid; done
check_experiment_launched_every:
  1