services:
  frontend:
    #platform: linux/amd64
    build:
      context: ../../
      dockerfile: ./dev/frontend/Dockerfile
      tags:
        - jesselin/frontend:v1
    tty: true
    stdin_open: true
    # volumes:
    #   - "../:/usr/src/"
