from auto_disc.utils.callbacks.on_discovery_callbacks.base_on_discovery_callback import BaseOnDiscoveryCallback
from auto_disc.utils.callbacks.on_discovery_callbacks.on_discovery_save_callback_on_disk import OnDiscoverySaveCallbackOnDisk
from auto_disc.utils.callbacks.on_discovery_callbacks.on_discovery_expe_db_save_callback import OnDiscoveryExpeDBSaveCallback