name: build-images

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      is_pull_request:
        required: true
        type: boolean
      sem_ver:
        required: false
        type: string
    secrets: inherit
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        # TODO: automate the generation of this list someday
        image:
          - "app"
          - "gateway"
          - "expe-db-api"
          - "autodisc-server"
          - "jupyter"
        include:
          - image: "app"
            context: "./services/base/FrontEndApp"
          - image: "gateway"
            context: "./services/base/Gateway"
          - image: "expe-db-api"
            context: "./services/base/ExpeDB/API"
          - image: "autodisc-server"
            context: "./services/base/AutoDiscServer"
          - image: "jupyter"
            context: "./services/base/JupyterLab"
    runs-on: ubuntu-latest
    env:
      SEMVER: ${{ inputs.is_propagated_pull_request && inputs.sem_ver || ''}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Retrieve relevant metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            registry.gitlab.inria.fr/cromac/automateddiscoverytool/${{ matrix.image }}
          tags: |
            type=raw,priority=1000,value=${{ env.SEMVER }}
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=sha-
      - name: Login to Gitlab registry
        if: github.event_name != 'pull_request' && inputs.is_propagated_pull_request = false
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.inria.fr/cromac/automateddiscoverytool
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' && inputs.is_propagated_pull_request = false }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
