name: commitlint
on: [pull_request]
jobs:
  commitlint:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          # fetch entire history
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5
