name: commitlint
on:
  workflow_dispatch
  # push:
  #   branches:
  #     - prod
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          # fetch entire history
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5
