name: format code

on:
  pull_request:

jobs:
  format-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # NOTE: isort should run before black as black formats the sort results
      - name: Run isort import sorter
        uses: isort/isort-action@v1
        with:
          configuration: "--check-only --profile black"
      - name: Run Black python formatter
        uses: psf/black@stable
        with:
          options: "--check"
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run Prettier formatter for JS/HTML/CSS/etc.
        uses: creyD/prettier_action@v4.3
