on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          pull-request-title-pattern: "chore${scope}: release${component} ${version}"
          release-type: simple
          default-branch: dev
