on:
  workflow_dispatch
  # push:
  #   branches:
  #     - dev

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: prod
          package-name: adtool
          release-as: 0.2.1
