on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

name: Release pipeline

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new semver release
        id: release-pr
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: dev
    outputs:
      releases_created: ${{ steps.release-pr.outputs.releases_created }}
      sem-ver: ${{ steps.release-pr.outputs.major }}.${{ steps.release-pr.outputs.minor }}.${{ steps.release-pr.outputs.patch }}
  build-and-deploy:
    needs: release-please
    if: jobs.release-please.outputs.releases_created
    uses: ./.github/workflows/build-images.yml
    with:
      push-images: true
      sem-ver: ${{ needs.release-please.outputs.sem-ver }}
