on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: dev
  build-docs:
    needs: release-pr
    uses: ./.github/workflows/build-docs.yml
  build-images:
    needs: release-pr
    uses: ./.github/workflows/build-images.yml
    with:
      is_pull_request: ${{ release-pr.releases_created }}
      sem_ver: ${{ release-pr.major }}.${{ release-pr.minor }}.${{ release-pr.patch }}
    secrets: inherit
