on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: dev
  build-docs:
    needs: release-pr
    uses: ./.github/workflows/build-docs.yml
    secrets: inherit
  build-images:
    needs: release-pr
    uses: ./.github/workflows/build-images.yml
    secrets: inherit
