from auto_disc_legacy.output_representations.specific.lenia_output_representation import LeniaImageRepresentation
from auto_disc_legacy.output_representations.specific.lenia_output_representation_hand_defined import LeniaHandDefinedRepresentation
